# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  batch: true
  branches:
    include:
      - master
      - develop
      - release/*

pr:
  branches:
    include:
      - master
      - release/*

pool:
  vmImage: 'windows-latest'

variables:
  Solution: '**/*.sln'
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.401'

- script: |
    dotnet tool install -g GitVersion.Tool --version 5.0.2-beta1.37
  displayName: 'Install global tools'

- script: dotnet-gitversion /output buildserver
  displayName: 'Run GitVersion.Tool'

- powershell: Write-Output "##vso[task.setvariable variable=informationalVersion]$($env:GITVERSION_INFORMATIONALVERSION)"
  displayName: 'Set assembly version variable'

- bash: printenv | sort
  displayName: 'List environment variables'

- task: DotNetCoreCLI@2
  displayName: 'Build source'
  inputs:
    command: 'build'
    projects: '$(Solution)'
    arguments: '-c $(BuildConfiguration) /p:Version=$(informationalVersion)'

- powershell: |
    $testsDirectory = Join-Path -Path '$(Build.SourcesDirectory)' -ChildPath 'tests'
    $testAssemblies = Get-ChildItem -Path "$testsDirectory" -Recurse -File -Filter '*.Tests.csproj' | Select-Object -ExpandProperty BaseName
    Write-Output "##vso[task.setvariable variable=testAssemblies]$($testAssemblies -join '|')"
  displayName: 'Set test assembly filter variable'

- task: DotNetCoreCLI@2
  displayName: 'Run tests with coverage'
  inputs:
    command: test
    projects: 'tests/**/*.Tests.csproj'
    arguments: '-c $(BuildConfiguration) /p:Version=$(informationalVersion) /p:AltCover=true /p:AltCoverOpenCover=true /p:AltCoverAssemblyExcludeFilter="xunit|$(testAssemblies)"'

- powershell: |
    $testsDirectory = Join-Path -Path '$(Build.SourcesDirectory)' -ChildPath 'tests'
    $coverageFile = Get-ChildItem -Path "$testsDirectory" -Recurse -File -Filter 'coverage.xml' | Select-Object -First 1
    $codecovExecutable = Get-ChildItem -Path "$ENV:USERPROFILE\.nuget\packages\codecov" -Recurse -File -Filter "codecov.exe" | Sort-Object -Descending -Property FullName | Select-Object -First 1
    & "$($codecovExecutable.FullName)" -f "$($coverageFile.FullName)" -t '$(CODECOV_TOKEN)'
  displayName: 'Upload coverage to codecov.io'

- task: DotNetCoreCLI@2
  displayName: 'Pack projects'
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  inputs:
    command: 'pack'
    packagesToPack: '$(Solution)'
    nobuild: true
    includesymbols: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'GITVERSION_NUGETVERSIONV2'

- task: NuGetToolInstaller@1
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  inputs:
    versionSpec: '5.1.0'
    checkLatest: true

- task: NuGetCommand@2
  displayName: 'Push *.nupkg and *.snupkg to nuget.org'
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'
    allowPackageConflicts: true

- task: GitHubRelease@0
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    gitHubConnection: 'GithubOAuth'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'manual'
    tag: 'v$(Build.BuildNumber)'
    title: 'v$(Build.BuildNumber)'

- task: GitHubRelease@0
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')))
  inputs:
    gitHubConnection: 'GithubOAuth'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'manual'
    tag: 'v$(Build.BuildNumber)'
    title: 'v$(Build.BuildNumber)'
    isPreRelease: true
